"""Regenerate Paper B figures from committed, provenance-locked artifacts.

Empirical figures read only frozen artifacts under docs/prereg/frozen/;
the theory figure (Fig 6) reads the two tracked theory-track tables
(docs/theory/t1_figure_data.json and t1_g2_density_scaling_results.json),
each regenerated byte-identically by its committed script. Palette:
Okabe-Ito (colorblind-safe; validated). Single y-axis per figure; series
sharing a figure share the same scale.

Usage: python docs/paper/paper_b/figures/make_figures.py
"""

from __future__ import annotations

import csv
import json
import statistics as st
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

FROZEN = Path("docs/prereg/frozen")
THEORY = Path("docs/theory")
OUT = Path("docs/paper/paper_b/figures")
BLUE = "#0072B2"  # truth-order error / structured / instrument
VERM = "#D55E00"  # held-out violation / foils / MM dimension
GREEN = "#009E73"  # null gap / height
ORANGE = "#E69F00"  # interval abundance / fixed-tube harvest
INK = "#222222"
MUTED = "#888888"
GRID = "#DDDDDD"


def _rows(name: str) -> list[dict]:
    return list(csv.DictReader(open(FROZEN / name)))


def _num(r: dict, k: str) -> float:
    try:
        return float(r[k])
    except (TypeError, ValueError):
        return float("nan")


def _d1_ok(rows: list[dict], condition: str) -> list[float]:
    return [
        _num(r, "heldout_violation")
        for r in rows
        if r.get("status") == "ok"
        and r.get("condition") == condition
        and r.get("embedding_dim") == "1.0"
    ]


def _style(ax) -> None:
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)
    for spine in ("left", "bottom"):
        ax.spines[spine].set_color(MUTED)
    ax.tick_params(colors=INK, labelsize=9)
    ax.yaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)


def figure_discriminator() -> None:
    """Fig 1: confirmatory held-out violation by condition (gate dim d=1)."""

    stage_b = _rows("pc_v1_stage_b_sensitivity.csv")
    stage_c = _rows("pc_v1_stage_c_specificity.csv")
    series = [
        ("structured\n(geometric)", _d1_ok(stage_b, "structured"), BLUE),
        ("random order\n(geometry-free)", _d1_ok(stage_c, "random_order"), VERM),
        (
            "column-shuffled\n(consistency-destroyed)",
            _d1_ok(stage_c, "column_shuffled"),
            VERM,
        ),
    ]
    fig, ax = plt.subplots(figsize=(6.4, 4.0))
    _style(ax)
    for i, (_label, vals, color) in enumerate(series):
        xs = [i + (j - len(vals) / 2) * 0.012 for j in range(len(vals))]
        ax.scatter(xs, vals, s=26, color=color, alpha=0.75, edgecolor="white",
                   linewidth=0.5, zorder=3)
        m = st.mean(vals)
        ax.plot([i - 0.22, i + 0.22], [m, m], color=INK, linewidth=2, zorder=4)
        ax.annotate(f"mean {m:.3f}", (i + 0.24, m), fontsize=8, color=INK,
                    va="center")
    ax.axhline(0.05, color=MUTED, linestyle="--", linewidth=1.2, zorder=2)
    ax.annotate("held-out gate = 0.05", (2.35, 0.065), fontsize=8, color=MUTED,
                ha="right")
    ax.set_xticks(range(len(series)))
    ax.set_xticklabels([s[0] for s in series], fontsize=9)
    ax.set_ylabel("held-out violation (d = 1)", fontsize=10, color=INK)
    ax.set_ylim(-0.02, 0.42)
    ax.set_title(
        "PC-V1: the pipeline passes on geometric order and blocks on\n"
        "matched geometry-free order (confirmatory seeds, frozen gate)",
        fontsize=10.5, color=INK, loc="left",
    )
    fig.tight_layout()
    fig.savefig(OUT / "fig1_discriminator.png", dpi=200)
    plt.close(fig)


def figure_dose_response() -> None:
    """Fig 2: P1 geometry-dilution dose-response with the false-pass window."""

    rows = [
        r
        for r in _rows("p1_stage_b_epsilon_sweep.csv")
        if r.get("status") == "ok" and _num(r, "density_held") == 1.0
    ]
    grid = [0.0, 0.15, 0.3, 0.45, 0.6, 0.75, 0.9, 1.0]

    def series(col: str) -> tuple[list[float], list[float], list[float]]:
        means, sds, eps = [], [], []
        for e in grid:
            cells = [_num(r, col) for r in rows if _num(r, "epsilon") == e]
            if cells:
                eps.append(e)
                means.append(st.mean(cells))
                sds.append(st.pstdev(cells) if len(cells) > 1 else 0.0)
        return eps, means, sds

    e_t, truth, truth_sd = series("truth_order_error")
    e_h, held, held_sd = series("heldout_violation")

    fig, ax = plt.subplots(figsize=(6.8, 4.4))
    _style(ax)

    # false-pass window: between truth crossing (~0.31) and heldout crossing (~0.50)
    ax.axvspan(0.31, 0.50, color=MUTED, alpha=0.12, zorder=0)
    ax.annotate("false-pass window\n(embeds, but not true space)",
                (0.405, 0.44), fontsize=8, color=MUTED, ha="center")

    for eps, mean, sd, color, label in (
        (e_t, truth, truth_sd, BLUE, "truth-order error (space recovery)"),
        (e_h, held, held_sd, VERM, "held-out violation (embeddability)"),
    ):
        lo = [m - s for m, s in zip(mean, sd, strict=True)]
        hi = [m + s for m, s in zip(mean, sd, strict=True)]
        ax.fill_between(eps, lo, hi, color=color, alpha=0.15, zorder=1)
        ax.plot(eps, mean, color=color, linewidth=2, marker="o", markersize=5,
                zorder=3, label=label)

    ax.axhline(0.15, color=BLUE, linestyle=":", linewidth=1.1, zorder=2)
    ax.axhline(0.05, color=VERM, linestyle=":", linewidth=1.1, zorder=2)
    ax.annotate("truth gate 0.15", (1.0, 0.16), fontsize=7.5, color=BLUE, ha="right")
    ax.annotate("held-out gate 0.05", (1.0, 0.06), fontsize=7.5, color=VERM, ha="right")
    ax.axvline(0.31, color=INK, linestyle="-", linewidth=0.8, alpha=0.5, zorder=2)
    ax.annotate("epsilon* ~ 0.31", (0.31, -0.045), fontsize=8, color=INK, ha="center")

    ax.set_xlabel("geometry dilution  epsilon   (0 = Minkowski, 1 = geometry-free)",
                  fontsize=10, color=INK)
    ax.set_ylabel("sign-discordance / violation fraction", fontsize=10, color=INK)
    ax.set_xlim(-0.03, 1.03)
    ax.set_ylim(-0.06, 0.58)
    ax.legend(loc="upper left", fontsize=8.5, frameon=False)
    ax.set_title(
        "P1: geometry recovery degrades monotonically as order is diluted\n"
        "at fixed relation density (~0.57 across all epsilon; bands = +/-1 SD)",
        fontsize=10.5, color=INK, loc="left",
    )
    fig.tight_layout()
    fig.savefig(OUT / "fig2_dose_response.png", dpi=200)
    plt.close(fig)


def figure_confound() -> None:
    """Fig 7: the shared-scalar confound — raw vs parallax dissimilarity.

    Slopegraph on the geometry-free control (PC-V1 Stage C seeds). Each line is
    one seed's d=1 held-out violation under raw bracket-width dissimilarity
    (left, shared scalar retained) and parallax dissimilarity (right, shared
    scalar removed). Reads confound_data.csv (compute_confound_data.py); the
    parallax column reproduces the frozen Stage C result exactly.
    """

    rows = list(csv.DictReader(open(OUT / "confound_data.csv")))
    raw = [float(r["raw"]) for r in rows]
    par = [float(r["parallax"]) for r in rows]
    gate = 0.05

    fig, ax = plt.subplots(figsize=(6.2, 4.4))
    _style(ax)
    ax.axhspan(-0.02, gate, color=MUTED, alpha=0.10, zorder=0)
    ax.axhline(gate, color=MUTED, linestyle="--", linewidth=1.2, zorder=2)
    ax.annotate("gate 0.05", (1.5, gate), fontsize=8, color=MUTED, va="center",
                ha="right")
    ax.annotate("shaded = passes the gate\n(false-pass for geometry-free input)",
                (-0.33, 0.012), fontsize=8, color=MUTED, ha="left", va="center")

    for r_val, p_val in zip(raw, par, strict=True):
        ax.plot([0, 1], [r_val, p_val], color=MUTED, linewidth=1.0, alpha=0.6,
                zorder=2)
        raw_color = VERM if r_val <= gate else INK
        ax.scatter([0], [r_val], s=34, color=raw_color, zorder=3,
                   edgecolor="white", linewidth=0.5)
        ax.scatter([1], [p_val], s=34, color=BLUE, zorder=3,
                   edgecolor="white", linewidth=0.5)

    for x, vals in ((0, raw), (1, par)):
        m = sum(vals) / len(vals)
        ax.plot([x - 0.09, x + 0.09], [m, m], color=INK, linewidth=2.5, zorder=4)
        ax.annotate(f"mean {m:.3f}", (x, m + 0.018), fontsize=8.5, color=INK,
                    ha="center")

    false_pass = sum(1 for v in raw if v <= gate)
    ax.set_xticks([0, 1])
    ax.set_xticklabels([
        "raw dissimilarity\n(shared scalar retained)",
        "parallax dissimilarity\n(shared scalar removed)",
    ], fontsize=9.5)
    ax.set_xlim(-0.35, 1.5)
    ax.set_ylim(-0.02, 0.36)
    ax.set_ylabel("held-out violation (d = 1)", fontsize=10, color=INK)
    ax.set_title(
        "PC-V1 confound: on geometry-free order, raw dissimilarity sits at the\n"
        f"gate ({false_pass}/{len(raw)} false-pass); parallax centering blocks all "
        f"{len(par)}/{len(par)}",
        fontsize=10.5, color=INK, loc="left",
    )
    fig.tight_layout()
    fig.savefig(OUT / "fig7_confound.png", dpi=200)
    plt.close(fig)


def figure_dimension_2d() -> None:
    """Fig 3: 2+1D dimension selection (P2-v2 confirmatory)."""

    rows = [
        r
        for r in _rows("p2_v2_stage_b_2plus1d.csv")
        if r.get("status") == "ok"
    ]
    dims = [1, 2, 3]
    truth = {d: [_num(r, f"d{d}_truth") for r in rows] for d in dims}
    gate = 0.15  # frozen P2-v2 truth gate

    fig, ax = plt.subplots(figsize=(6.2, 4.2))
    _style(ax)
    ax.axhline(gate, color=MUTED, linestyle="--", linewidth=1.2, zorder=2)
    ax.annotate("truth gate 0.15", (2.4, gate + 0.008), fontsize=8, color=MUTED,
                ha="right")
    for i, d in enumerate(dims):
        vals = truth[d]
        xs = [i + (j - len(vals) / 2) * 0.010 for j in range(len(vals))]
        color = VERM if d == 1 else BLUE
        ax.scatter(xs, vals, s=24, color=color, alpha=0.75, edgecolor="white",
                   linewidth=0.5, zorder=3)
        m = st.mean(vals)
        ax.plot([i - 0.2, i + 0.2], [m, m], color=INK, linewidth=2.2, zorder=4)
        ax.annotate(f"mean {m:.3f}", (i + 0.24, m), fontsize=8, color=INK,
                    va="center")
    ax.set_xticks(range(len(dims)))
    ax.set_xticklabels(
        ["d = 1\n(underfits)", "d = 2\n(recovers 2D)", "d = 3\n(no gain)"],
        fontsize=9.5,
    )
    ax.set_ylabel("truth-order error vs true 2D position", fontsize=10, color=INK)
    ax.set_ylim(0.0, 0.32)
    ax.set_title(
        "2+1D dimension selection (P2-v2, confirmatory): recovery needs d = 2\n"
        "and saturates there -- d = 1 underfits, d = 3 adds nothing",
        fontsize=10.5, color=INK, loc="left",
    )
    fig.tight_layout()
    fig.savefig(OUT / "fig3_dimension_2d.png", dpi=200)
    plt.close(fig)


def figure_emergence_chain() -> None:
    """Fig 5: the emergence chain in one row — P3 null | P4 phases | P5 verdict.

    Panel A: P3 percolation sweep (held-out violation where six chains exist;
    structural-block counts where they do not; sprinkled P3-A reference band).
    Panel B: P4 dual-start mean action vs beta (hysteresis opens at beta 3-4;
    exact bipartite floor -120). Panel C: P5 per-configuration gate metrics vs
    beta with the uniform-ensemble calibration at beta = 0 and the structural
    block at beta = 32.
    """

    fig, (ax_a, ax_b, ax_c) = plt.subplots(1, 3, figsize=(12.8, 4.3))
    for ax in (ax_a, ax_b, ax_c):
        _style(ax)

    # --- Panel A: P3 percolation sweep -----------------------------------
    p3 = _rows("p3_stage_b_dynamics.csv")
    cal3 = [_num(r, "heldout") for r in _rows("p3_stage_a_calibration.csv")
            if r.get("status") == "ok"]
    grid_p = sorted({_num(r, "p") for r in p3})
    ax_a.axhspan(min(cal3), max(cal3), color=BLUE, alpha=0.15, zorder=0)
    ax_a.annotate("sprinkled 1+1D reference (P3-A, passes)",
                  (grid_p[0], max(cal3) + 0.012), fontsize=7.5, color=BLUE)
    ax_a.axhline(0.10, color=MUTED, linestyle="--", linewidth=1.2, zorder=2)
    ax_a.annotate("held-out gate 0.10", (grid_p[-1], 0.108), fontsize=7.5,
                  color=MUTED, ha="right")
    for p in grid_p:
        rows = [r for r in p3 if _num(r, "p") == p]
        ok = [_num(r, "heldout") for r in rows if r.get("status") == "ok"]
        blocked = len(rows) - len(ok)
        xs = [p + (j - len(ok) / 2) * 0.00012 for j in range(len(ok))]
        ax_a.scatter(xs, ok, s=22, color=VERM, alpha=0.75, edgecolor="white",
                     linewidth=0.5, zorder=3)
        ax_a.annotate(f"{blocked}/20", (p, 0.372), fontsize=7, color=MUTED,
                      ha="center")
    ax_a.annotate("structurally blocked runs (no six 25-tick chains)",
                  (grid_p[-1], 0.345), fontsize=7, color=MUTED, ha="right")
    ax_a.set_xticks(grid_p)
    ax_a.set_xticklabels([f"{p:g}" for p in grid_p], fontsize=8.5)
    ax_a.set_xlabel("percolation probability p", fontsize=9.5, color=INK)
    ax_a.set_ylabel("held-out violation", fontsize=9.5, color=INK)
    ax_a.set_ylim(0.0, 0.40)
    ax_a.set_title("P3: transitive percolation\n0/100 pass (blocks at every p)",
                   fontsize=10, color=INK, loc="left")

    # --- Panel B: P4 dual-start hysteresis --------------------------------
    p4 = _rows("p4_stage_b_sweep.csv")
    betas4 = sorted({_num(r, "beta") for r in p4})
    ax_b.axvspan(2.5, 4.5, color=MUTED, alpha=0.10, zorder=0)
    ax_b.annotate("continuum", (1.0, 15), fontsize=8, color=MUTED, ha="center")
    ax_b.annotate("transition\n(hysteresis)", (3.5, 15), fontsize=8,
                  color=MUTED, ha="center")
    ax_b.annotate("crystal", (5.6, 15), fontsize=8, color=MUTED, ha="center")
    ax_b.axhline(-120, color=INK, linestyle="--", linewidth=1.0, alpha=0.6,
                 zorder=2)
    ax_b.annotate("exact bipartite S = -120", (0.0, -117), fontsize=7.5,
                  color=INK, alpha=0.8)
    for start, color, marker, label in (
        ("R", BLUE, "o", "random start"),
        ("X", VERM, "s", "crystal (bipartite) start"),
    ):
        means = []
        for b in betas4:
            vals = [_num(r, "S") for r in p4
                    if _num(r, "beta") == b and r.get("start") == start]
            xs = [b + (j - len(vals) / 2) * 0.02 for j in range(len(vals))]
            ax_b.scatter(xs, vals, s=18, color=color, alpha=0.55,
                         edgecolor="white", linewidth=0.4, zorder=3,
                         marker=marker)
            means.append(st.mean(vals))
        ax_b.plot(betas4, means, color=color, linewidth=1.8, marker=marker,
                  markersize=5, zorder=4, label=label)
    ax_b.set_xticks(betas4)
    ax_b.set_xticklabels([f"{b:g}" for b in betas4], fontsize=8.5)
    ax_b.set_xlabel("coupling beta", fontsize=9.5, color=INK)
    ax_b.set_ylabel("chain mean action <S>", fontsize=9.5, color=INK)
    ax_b.legend(loc="center left", fontsize=8, frameon=False)
    ax_b.set_title("P4: 2D-orders phases (N = 100)\nhysteretic crystallization",
                   fontsize=10, color=INK, loc="left")

    # --- Panel C: P5 discriminator verdict --------------------------------
    # beta = 32 rows come from the shard schema (acc, beta, chain_S, sample,
    # seed, status): DictReader leaves null_gap/truth unset for them.
    p5 = _rows("p5_stage_b_all.csv")
    ok5 = [r for r in p5 if r.get("status") == "ok"]
    cal5 = [r for r in _rows("p5_stage_a_calibration.csv")
            if r.get("status") == "ok"]
    n_blocked = len(p5) - len(ok5)
    groups = [("0\n(uniform cal.)", cal5),
              ("2", [r for r in ok5 if _num(r, "beta") == 2.0]),
              ("8", [r for r in ok5 if _num(r, "beta") == 8.0])]
    ax_c.axhline(0.10, color=MUTED, linestyle="--", linewidth=1.2, zorder=2)
    ax_c.annotate("gate 0.10", (3.5, 0.112), fontsize=7.5, color=MUTED,
                  ha="right")
    ax_c.axhline(0.50, color=BLUE, linestyle=":", linewidth=1.0, zorder=2)
    ax_c.annotate("truth chance level 0.5", (3.45, 0.515), fontsize=7.5,
                  color=BLUE, ha="right")
    for series_key, color, marker, dx, label in (
        ("heldout", VERM, "o", -0.18, "held-out violation"),
        ("null_gap", GREEN, "^", 0.0, "null gap"),
        ("truth", BLUE, "s", 0.18, "truth-order error"),
    ):
        for i, (_lbl, rows) in enumerate(groups):
            vals = [_num(r, series_key) for r in rows]
            xs = [i + dx + (j - len(vals) / 2) * 0.014 for j in range(len(vals))]
            ax_c.scatter(xs, vals, s=22, color=color, alpha=0.75,
                         edgecolor="white", linewidth=0.5, zorder=3,
                         marker=marker, label=label if i == 0 else None)
    ax_c.axvspan(2.6, 3.4, color=MUTED, alpha=0.12, zorder=0)
    ax_c.annotate(f"structural block\n(0 chains, {n_blocked}/{n_blocked})",
                  (3.0, 0.30), fontsize=8, color=MUTED, ha="center")
    ax_c.set_xticks([0, 1, 2, 3])
    ax_c.set_xticklabels([g[0] for g in groups] + ["32\n(crystal)"],
                         fontsize=8.5)
    ax_c.set_xlim(-0.55, 3.55)
    ax_c.set_ylim(0.0, 0.70)
    ax_c.set_xlabel("coupling beta", fontsize=9.5, color=INK)
    ax_c.set_ylabel("gate metric", fontsize=9.5, color=INK)
    ax_c.legend(loc="upper left", fontsize=8, frameon=False)
    ax_c.set_title("P5: discriminator verdict (N = 600)\n18/18 pass; crystal blocked",
                   fontsize=10, color=INK, loc="left")

    fig.tight_layout()
    fig.savefig(OUT / "fig5_emergence_chain.png", dpi=200)
    plt.close(fig)


def _rank_auc(labels: list[int], scores: list[float]) -> float:
    """Mann-Whitney AUC with average ranks (matches p6_diagnostics.roc_auc)."""

    values = np.asarray(scores, dtype=float)
    order = np.argsort(values, kind="mergesort")
    ranks_sorted = np.arange(1, values.size + 1, dtype=float)
    sorted_values = values[order]
    start = 0
    while start < values.size:
        stop = start + 1
        while stop < values.size and sorted_values[stop] == sorted_values[start]:
            stop += 1
        ranks_sorted[start:stop] = 0.5 * (start + 1 + stop)
        start = stop
    ranks = np.empty(values.size, dtype=float)
    ranks[order] = ranks_sorted
    positives = np.asarray(labels, dtype=int) == 1
    n_pos = int(positives.sum())
    n_neg = int(values.size - n_pos)
    return float(
        (ranks[positives].sum() - n_pos * (n_pos + 1) / 2) / (n_pos * n_neg)
    )


def _roc_points(labels: list[int], scores: list[float]):
    """Step ROC curve; tied scores collapse to one threshold point."""

    values = np.asarray(scores, dtype=float)
    order = np.argsort(-values, kind="mergesort")
    y = np.asarray(labels, dtype=int)[order]
    sorted_values = values[order]
    tp = np.cumsum(y)
    fp = np.cumsum(1 - y)
    last_of_tie = np.r_[np.flatnonzero(np.diff(sorted_values)), y.size - 1]
    tpr = np.r_[0.0, tp[last_of_tie] / tp[-1]]
    fpr = np.r_[0.0, fp[last_of_tie] / fp[-1]]
    return fpr, tpr


def _order_only_margin(row: dict) -> float:
    """The frozen instrument margin with the truth-gate term removed
    (order-only gates: held-out violation and null gap; Section 7.6)."""

    if row["status"] != "ok":
        return -5.0
    heldout = float(row["heldout"])
    if row["source"] == "P1":
        return (0.05 - heldout) / 0.05
    margins = [(0.10 - heldout) / 0.10]
    if row.get("null_gap", "") != "":
        margins.append((float(row["null_gap"]) - 0.10) / 0.10)
    return min(margins)


def figure_p6b_comparison() -> None:
    """Fig 4: P6b head-to-head — ROC curves and the H-LAG safety check.

    Reads the frozen per-row table and the frozen summary; recomputes each
    AUC with the registry's rank convention and asserts equality with the
    frozen values, so the figure can never silently disagree with the
    registry. The order-only instrument variant (truth term removed) is the
    descriptive recomputation of Section 7.6.
    """

    rows = [r for r in _rows("p6b_scored_rows.csv") if r.get("label") != ""]
    summary = json.loads((FROZEN / "p6b_diagnostics_summary.json").read_text())
    labels = [int(float(r["label"])) for r in rows]

    series = [
        ("instrument margin", [float(r["instrument_margin"]) for r in rows],
         BLUE, "-"),
        ("MM-dimension distance", [-float(r["mm_distance"]) for r in rows],
         VERM, "-"),
        ("height distance", [-float(r["height_distance"]) for r in rows],
         GREEN, "-"),
        ("abundance distance", [-float(r["abundance_distance"]) for r in rows],
         ORANGE, "-"),
    ]
    frozen_auc_keys = ("instrument_margin", "mm_distance",
                      "height_distance", "abundance_distance")
    for (label, scores, _c, _ls), key in zip(series, frozen_auc_keys,
                                             strict=True):
        auc = _rank_auc(labels, scores)
        frozen = float(summary["roc_auc"][key])
        assert abs(auc - frozen) < 1e-9, (label, auc, frozen)
    order_only = [_order_only_margin(r) for r in rows]
    auc_order_only = _rank_auc(labels, order_only)
    assert abs(auc_order_only - 0.9931) < 1e-4, auc_order_only
    series.insert(1, ("order-only margin (no truth term)", order_only,
                      BLUE, "--"))

    fig, (ax_roc, ax_bar) = plt.subplots(
        1, 2, figsize=(10.6, 4.3), gridspec_kw={"width_ratios": [1.45, 1.0]}
    )
    for ax in (ax_roc, ax_bar):
        _style(ax)

    ax_roc.plot([0, 1], [0, 1], color=MUTED, linestyle=":", linewidth=1.0,
                zorder=1)
    for label, scores, color, style in series:
        fpr, tpr = _roc_points(labels, scores)
        auc = _rank_auc(labels, scores)
        ax_roc.plot(fpr, tpr, color=color, linestyle=style, linewidth=1.8,
                    zorder=3, label=f"{label} (AUC {auc:.3f})")
    ax_roc.set_xlim(-0.02, 1.0)
    ax_roc.set_ylim(0.0, 1.02)
    ax_roc.set_xlabel("false-positive rate (non-geometric passing)",
                      fontsize=9.5, color=INK)
    ax_roc.set_ylabel("true-positive rate (geometric passing)",
                      fontsize=9.5, color=INK)
    ax_roc.legend(loc="lower right", fontsize=8, frameon=False)
    ax_roc.set_title(
        "ROC on the 362 frozen-labelled orders\n"
        "(58 geometric vs 304 non-geometric)",
        fontsize=10, color=INK, loc="left",
    )

    overlap = summary["p1_h_lag_overlap"]
    cheap = (("MM dim.", "mm_distance", VERM),
             ("height", "height_distance", GREEN),
             ("abundance", "abundance_distance", ORANGE))
    n_h_lag = int(overlap["mm_distance"]["n_h_lag"])
    counts = [int(overlap[key]["n_false_pass"]) for _lbl, key, _c in cheap]
    ax_bar.bar([c[0] for c in cheap], counts, color=[c[2] for c in cheap],
               width=0.55, zorder=3)
    for i, count in enumerate(counts):
        ax_bar.annotate(f"{count}/{n_h_lag}", (i, count + 0.5), fontsize=9,
                        color=INK, ha="center")
    ax_bar.set_ylim(0, n_h_lag + 3.5)
    ax_bar.axhline(n_h_lag, color=MUTED, linestyle="--", linewidth=1.0,
                   zorder=2)
    ax_bar.annotate(f"all {n_h_lag} H-LAG cells", (1.0, n_h_lag + 0.6),
                    fontsize=8, color=MUTED, ha="center")
    ax_bar.set_ylabel("cells called geometric (false pass)", fontsize=9.5,
                      color=INK)
    ax_bar.set_title(
        "P1 H-LAG window: cells that embed\nbut are not true space "
        "(instrument-defined)",
        fontsize=10, color=INK, loc="left",
    )

    fig.tight_layout()
    fig.savefig(OUT / "fig4_p6b_comparison.png", dpi=200)
    plt.close(fig)


def figure_theory() -> None:
    """Fig 6: the theory of Section 8, on its verified data.

    Panel A: Model-D quantization band (Lemma 2) at the pinned controlled
    configuration. Panel B: the 1/K resolution law (Section 8.3). Panel C:
    protocol-dependent density scaling (Section 8.4). Reads the two tracked
    theory tables; asserts the band and the slope so the figure cannot
    drift from the manuscript's quoted numbers.
    """

    fig_data = json.loads((THEORY / "t1_figure_data.json").read_text())
    density = json.loads(
        (THEORY / "t1_g2_density_scaling_results.json").read_text()
    )

    fig, (ax_a, ax_b, ax_c) = plt.subplots(1, 3, figsize=(12.8, 4.2))
    for ax in (ax_a, ax_b, ax_c):
        _style(ax)

    # --- Panel A: quantization band ---------------------------------------
    band = fig_data["band"]
    assert band["violations"] == 0, band
    x = np.asarray(band["abs_dx_over_delta"], dtype=float)
    w = np.asarray(band["measured_w"], dtype=float)
    grid = np.linspace(0.0, float(x.max()) * 1.02, 200)
    ax_a.fill_between(grid, 2 * grid, 2 * grid + 2, color=MUTED, alpha=0.18,
                      zorder=1)
    ax_a.plot(grid, 2 * grid + 1, color=INK, linewidth=1.2, zorder=2,
              label="center 2|dx|/delta + 1")
    ax_a.scatter(x, w, s=14, color=BLUE, alpha=0.6, edgecolor="white",
                 linewidth=0.3, zorder=3, label="measured W")
    ax_a.annotate(
        f"{band['n_reachable']}/{band['n_reachable']} in band "
        "(0 violations;\nband half-open, theta in [-1, 1))",
        (0.03, 0.86), xycoords="axes fraction", fontsize=8, color=INK,
    )
    ax_a.set_xlabel("|dx| / delta  (tick units)", fontsize=9.5, color=INK)
    ax_a.set_ylabel("bracket width W  (rank units)", fontsize=9.5, color=INK)
    ax_a.legend(loc="lower right", fontsize=8, frameon=False)
    ax_a.set_title("Model D: deterministic quantization band\n"
                   "(400 controlled targets, K = 96, seed-pinned)",
                   fontsize=10, color=INK, loc="left")

    # --- Panel B: 1/K resolution law --------------------------------------
    resolution = fig_data["resolution"]
    slope = float(resolution["rmse_loglog_slope"])
    assert -1.3 < slope < -0.7, slope
    k_minus_1 = np.array([row["ticks"] - 1 for row in resolution["ladder"]],
                         dtype=float)
    rmse = np.array([row["rmse"] for row in resolution["ladder"]], dtype=float)
    bound = np.array([row["bound_delta_over_2"] for row in resolution["ladder"]],
                     dtype=float)
    ax_b.loglog(k_minus_1, bound, color=MUTED, linestyle="--", linewidth=1.2,
                zorder=2, label="proved pointwise bound delta/2")
    ax_b.loglog(k_minus_1, rmse, color=BLUE, marker="o", markersize=5,
                linewidth=1.8, zorder=3, label="measured RMSE of |dx|-hat")
    ax_b.annotate(f"log-log slope {slope:.3f}", (0.05, 0.08),
                  xycoords="axes fraction", fontsize=9, color=INK)
    ax_b.set_xlabel("K - 1  (ticks)", fontsize=9.5, color=INK)
    ax_b.set_ylabel("radial-distance error", fontsize=9.5, color=INK)
    ax_b.legend(loc="upper right", fontsize=8, frameon=False)
    ax_b.set_title("resolution-limited stability: RMSE ~ 1/K\n"
                   "(every pointwise error within delta/2)",
                   fontsize=10, color=INK, loc="left")

    # --- Panel C: density scaling is protocol-dependent -------------------
    arms = density["arms"]
    thinned = arms["thinned"]["rows"]
    rho = np.array([row["rho"] for row in thinned], dtype=float)
    ax_c.loglog(rho, [row["rmse_predicted"] for row in thinned], color=BLUE,
                linestyle="--", linewidth=1.2, zorder=2,
                label="thinned: exact prediction")
    # order-only wandering identification (Section 8.4): asserted so the
    # figure cannot drift from the quoted KPZ classification
    recorded = density["order_only_recorded_expectations"]["outcomes"]
    assert (
        recorded["nearest_wandering_candidate"] == "kpz_wandering_-1/6"
    ), recorded
    assert abs(recorded["transverse_rms_exponent"] + 1.0 / 6.0) < 0.05, recorded
    # the count-class reading quoted in Section 8.4: the residual interval
    # alone would keep only the KPZ-like candidate, and the proved arm's
    # interval must cover its proved exponent (calibration of the machinery)
    status = density["count_class_status"]
    assert status["candidates_inside_ci95"] == {
        "poisson_rate_-1/4": False,
        "kpz_like_-1/3": True,
    }, status
    thinned_ci = arms["thinned"]["exponent_uncertainty"]["rmse"]["ci95"]
    assert thinned_ci[0] <= -0.5 <= thinned_ci[1], thinned_ci
    for key, color, marker, label in (
        ("thinned", BLUE, "o", "thinned clock, lam = rho*ell"),
        ("harvest_scaled", VERM, "s", "harvested chain, scaled tube"),
        ("harvest_fixed", ORANGE, "^", "harvested chain, fixed tube"),
        ("harvest_order_only", GREEN, "D", "harvested chain, order-only"),
    ):
        rows = arms[key]["rows"]
        exponent = float(arms[key]["rmse_exponent"])
        low, high = arms[key]["exponent_uncertainty"]["rmse"]["ci95"]
        ax_c.loglog([row["rho"] for row in rows], [row["rmse"] for row in rows],
                    color=color, marker=marker, markersize=5, linewidth=1.8,
                    zorder=3,
                    label=f"{label}\n    exp {exponent:.2f} "
                          f"[{low:.2f}, {high:.2f}]")
    ax_c.set_xlabel("sprinkling density rho", fontsize=9.5, color=INK)
    ax_c.set_ylabel("radial-distance RMSE", fontsize=9.5, color=INK)
    ax_c.legend(loc="lower left", fontsize=8, frameon=False)
    ax_c.set_title("density scaling is protocol-dependent\n"
                   "(rho^-1/2 holds only for the thinned clock)",
                   fontsize=10, color=INK, loc="left")

    fig.tight_layout()
    fig.savefig(OUT / "fig6_theory.png", dpi=200)
    plt.close(fig)


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    figure_discriminator()      # Fig 1 (PC-V1, Section 4)
    figure_dose_response()      # Fig 2 (P1, Section 5)
    figure_dimension_2d()       # Fig 3 (P2-v2 robustness, Section 6)
    figure_p6b_comparison()     # Fig 4 (P6b head-to-head, Section 7.6)
    figure_emergence_chain()    # Fig 5 (emergence chain, Section 7.7)
    figure_theory()             # Fig 6 (T1 theory, Section 8)
    figure_confound()           # Fig 7 (confound, Discussion Section 9)
    for name in ("fig1_discriminator", "fig2_dose_response",
                 "fig3_dimension_2d", "fig4_p6b_comparison",
                 "fig5_emergence_chain", "fig6_theory", "fig7_confound"):
        print("wrote", OUT / f"{name}.png")
